version: '3.8'

services:
  honeygain:
    container_name: Honeygain
    image: honeygain/honeygain
    restart: always
    command: -tou-accept -email ${EMAIL} -pass ${PASSWORD} -device "HoneyGain"
    dns:
      - 1.1.1.1
      - 8.8.8.8

  honeygain-bot:
    container_name: Honeygain-bot
    build: . # <-- Importante: construir desde el Dockerfile del repo
    restart: unless-stopped
    environment:
      # Usar los nombres que espera tu bot.js
      - EMAIL=${EMAIL} # <-- Mapea la variable
      - PASSWORD=${PASSWORD} # <-- Mapea la variable
      - TZ=${TZ:-UTC} # <-- Opcional
    dns:
      - 1.1.1.1
      - 8.8.8.8
    # depends_on no es estrictamente necesario aquí
